apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: infra
  template:
    metadata:
      labels:
        app: infra
    spec:
      containers:
        - image: han51361/infra:latest
          name: infra-app
          ports:
            - containerPort: 8080